### ISSUE TITLE
A List of Questions and Quick Observations for JobSet

### ISSUE THREAD

**Issue by vsoch** [kubernetes-sigs/jobset#132]
Hiya! I'm using JobSet in the Flux Operator, and have some discussion / feedback:

### NonIndexedJob should support headless service
I'm creating a design with a leader and workers (a listing of two under the JobSet) and for the leader, I wanted to generate the headless service. But it gave me an error early on that I needed to use an IndexedJob. Is there a reason to not be able to create the service for a non-indexed job?

### Pod names are long bois
The names for the pods for the jobset are really long! The shorter ones for just having an indexed job are really much nicer to look at / query (e.g., `flux-sample-0-xxxx`) - could there be some way to reduce the length of the name? I would suspect it's about namespacing it to the jobset -> replicatedjob -> job but it's coming at the cost of the user experience I think.

### Creation time is slow
I'm not sure why, but I noticed that the time that I apply the minicluster.yaml (that creates the jobset) to then see the pods appear is fairly long, at least longer than if I just created the Indexed Job. This could just be an artifact of needing to use JobSet from a separate operator... or MiniKube being slow again (my computer is burning my legs right now so it might be that too!) :laughing: 

### Suspend makes it hard to debug
When I started with `suspend: true` I never saw any pods, and I think this is because it fails the JobSet on any failure. We might eventually want this to Complete pods, although with the new design we probably don't need it anymore. I'll leave it off for now because I didn't like my JobSet suspending without me being able to debug!

### Networking - allow me to set (shared) name?
It would be nice if two replicated jobs could be put under the same networking space - I actually couldn't get it working for the worker/broker to see one another. It wasn't a limit of the networking, but flux expects the result of `hostname` to be findable in the network, and since that isn't a FQDN for our cluster we did a hack to define a common default connect address (shown below). The problem is that there can only be one, but with two ReplicatedJob I have two! So either the broker doesn't see the worker or vice versa. I could talk to the Flux devs about if it's possible to allow two, but that theoretically would mean two checks and it's not ideal. 

I tried disabling the network, and created the service on my own, to be shared between the pods, and to get that working I had to use a new selector `job-group` instead of `job-name` that needs to be unique. That seems to work nicely, but we aren't getting anything from JobSet. I'll include the broker.toml config that we are using (and now working with JobSet and creating our own service) if you are interested:

```toml
[bootstrap]
curve_cert = "/etc/curve/curve.cert"
default_port = 8050
default_bind = "tcp://eth0:%p"

# These are the only two that matter - I can only put one global network name here
default_connect = "tcp://%h.flux-service.flux-operator.svc.cluster.local:%p"

# And the hosts here are checked under that namespace (so two doesn't work)
hosts = [
        { host="minicluster-flux-sample-broker-0-0, minicluster-flux-sample-worker-0-[0-2]"},
]
```

I also tried giving the two ReplicatedJobs the same Name, but that wasn't allowed. Per my suggestion (in the title) above, I wonder if different metadata-> Name could be allowed to be under the same service name? Maybe we could have:

```go
Network: &jobset.Network{
    Name: "flux-servicei",
    EnableDNSHostnames: &enableDNSHostnames,
},
```

And this would reproduce what I've manually created here. Aside from that - it was really fun testing this out! I learned a lot how to get this custom operator to be seen by mine, which came down to adding to the schema and the rbacs, and I really enjoyed trying out JobSet for the first time :partying_face: ! The work I did can be seen in https://github.com/flux-framework/flux-operator/pull/164/files#diff-21f0c3fe3a7f139c41d8288276b7493d269c34740b8dc6322b9c55514318c9e6. Looking forward to more discussion here!
