### ISSUE TITLE
Use case: Allow for jupyter or interactive notebooks via jobset

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/jobset#133]
Interactive jobs can be a very common usecase in HPC and/or DS/ML.  

I wanted to play around with using jobsets and I have the following example which creates a jupyter pod and a service.  However, maybe I don't understand headless services, but I am unable to access this service via a port-forward.  

My JS job:

```
apiVersion: jobset.x-k8s.io/v1alpha1
kind: JobSet
metadata:
  name: jupyter
spec:
  suspend: false
  replicatedJobs:
  - name: rj
    network:
      enableDNSHostnames: true
    template:
      spec:
        backoffLimit: 0
        template:
          spec:
            containers:
            - name: jupyterlab
              imagePullPolicy: IfNotPresent
              image: jupyter/tensorflow-notebook:latest
              securityContext:
                runAsUser: 1000
              resources:
                limits:
                  memory: 1Gi
                  cpu: 1
                requests:
                  memory: 1Gi
                  cpu: 1
              ports:
                - containerPort: 8888
                  name: jupyterlab
              env:
              - name: JUPYTER_TOKEN
                value: testing
 ```
 
 I can create an example usecase with a Job and a service manually.  Is it in scope to allow for jobset to support something like this?
 
 ```
apiVersion: batch/v1
kind: Job
metadata:
  name: jupyter-job
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      restartPolicy: Never
      containers:
      - name: jupyterlab
        imagePullPolicy: IfNotPresent
        image: jupyter/tensorflow-notebook:latest
        securityContext:
          runAsUser: 1000
        resources:
          limits:
            memory: 1Gi
            cpu: 1
          requests:
            memory: 1Gi
            cpu: 1
        ports:
        - containerPort: 8888
          name: jupyterlab
        env:
        - name: JUPYTER_TOKEN
          value: testing
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
spec:
  selector:
    app: jupyter
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
 ```
