### ISSUE TITLE
Allow setting enableDNSHostnames for non-indexed jobs

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/jobset#138]
**What would you like to be added**:

Allow setting enableDNSHostnames for non-indexed jobs

**Why is this needed**:

See discussion https://github.com/kubernetes-sigs/jobset/issues/132#issuecomment-1543348063

**Comment by vsoch** [comment]
Thank you for doing this! I tested it out, and can confirm it works great! It won't work for our case still (Flux Operator) because I realize that as a standard job, the hostname isn't predictable like it is with the indexed job. E.g. here is looking at hostname in the broker leader pod - it has the name of the pod:

```console
root@minicluster-flux-sample-broker-0-5jrtr:/code# hostname
minicluster-flux-sample-broker-0-5jrtr
```

And here is what a follower looks like:
```console
root@minicluster-flux-sample-worker-0-1:/code# hostname
minicluster-flux-sample-worker-0-1
```

Since we expect the names to be predictable to define for the broker config, `broker.toml`, requiring the full name of the pod (which is generated after creation) is not ideal / won't work.

```toml
[bootstrap]
curve_cert = "/etc/curve/curve.cert"
default_port = 8050
default_bind = "tcp://eth0:%p"
default_connect = "tcp://%h.flux-service.flux-operator.svc.cluster.local:%p"
hosts = [
        { host="minicluster-flux-sample-broker-0, minicluster-flux-sample-worker-0-[0-2]"},
]
```
so the solution for our case (or anyone else that needs this setup where the names are predictable before creating objects) is to just call the one pod job an indexed job, and then get the predictable naming.
