### ISSUE TITLE
JobSet TTL to clean up completed workloads

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#279]
We should look into having JobSet respect TTL so completed JobSets can be deleted from etcd and not take up space

https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/

**Comment by kannon92** [comment]
So I am a bit confused by this.

Are you saying we should have a field in JobSet that will purge JobSet from etcd giving a TTL?

Or are you wanting someone to test if one sets TTL in a Job, will the Job finish and then get deleted.  And even if the JobSet was marked as success (when Jobs all finish), the JobSet will recreate the finished job because it was deleted?

**Comment by kannon92** [comment]
So individual jobs can use ttl without any issue.

```
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: simple-with-ttl
spec:
  replicatedJobs:
  - name: leader
    replicas: 1
    template:
      spec:
        # Set backoff limit to 0 so job will immediately fail if any pod fails.
        backoffLimit: 0
        ttlSecondsAfterFinished: 60
        completions: 1
        parallelism: 1
        template:
          spec:
            containers:
            - name: leader
              image: bash:latest
              command:
              - bash
              - -xc
              - |
                sleep 100
  - name: workers
    replicas: 1
    template:
      spec:
        backoffLimit: 0
        ttlSecondsAfterFinished: 60
        completions: 2
        parallelism: 2
        template:
          spec:
            containers:
            - name: worker
              image: bash:latest
              command:
              - bash
              - -xc
              - |
                sleep 100
~                            
```

Jobs are cleaned up and deleted from etcd but JobSet will still mark this was successful.  

I think we could add a ttl for JobSet as the JobSet will not be deleted.  IMO this would be a nice feature for any CRD though..
