### ISSUE TITLE
Ability to launch any CR using jobset

### ISSUE THREAD

**Issue by asm582** [kubernetes-sigs/jobset#375]
**What would you like to be added**:

I think jobset currently supports batchv1 jobs. This can lead to users' inability to launch Flink or Spark pipeline.

**Why is this needed**:
Adding support for custom CRs will help in gang scheduling constraints of these custom CRDs using project Kueue.

**Comment by ahg-g** [comment]
Can you clarify the ask more with a concrete example? JobSet by design is an API to lunch a group of Jobs.

**Comment by asm582** [comment]
I am thinking about the ability of Jobset to wrap any CRs:

```
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: wrapped user gang CR
spec:
  replicatedJobs:
    - name: workers
      template:
        spec:
          #CR with gang of 4 
          parallelism: 4
          completions: 4
          #wrapped the entire user-submitted CR
          apiversion: x.x.spark or x.x.flink
          Kind: spark or flink 
        
```
In the above use case, jobset is a wrapper for any user-submitted CRs. This may help users who do not wish to move to batchv1 jobs explicitly.
