### ISSUE TITLE
Support Autoscaling replicatedJob

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/jobset#570]
**What would you like to be added**:
I would like to support [scale subresource](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource) and the metrics corresponding to HPA resource like this:

```yaml
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: autoscaling-sample
spec:
  scalePolicy:
    replicatedJobName:  workers  # Job Name
    replicas: 2                  # scaling target
    autoScaling:                 # typed `[]autoscalingv2.MetricSpec`
      minReplicas: 1
      maxReplicas: 10
      metrics:
        [...] 
  replicatedJobs:
  - name: workers
[...]
```

**Why is this needed**:
In the machine learning field, we often support elastically scaling worker nodes such as [PyTorch Elastic](https://pytorch.org/docs/stable/elastic/run.html).
Here is Kubeflow TrainingOperator Example: https://github.com/kubeflow/training-operator/blob/e31d11faa9f6ce5111b60c01079d39295589e0ef/pkg/apis/kubeflow.org/v1/pytorch_types.go#L98-L135
