### ISSUE TITLE
Support Stateful JobSet

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/jobset#572]
**What would you like to be added**:
I would like to support features to create a single PVC and mount the PV to some replicatedJobs like this:

```yaml
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: volume-sample
spec:
  volumePolicy:
    replicatedJobs:
     - name: A
     - name: B
    volumeClaimTemplates:
    - metadata:
        name: pretrained-model
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: "my-storage-class"
        resources:
          requests:
            storage: 1000Gi
  replicatedJobs:
  - name: workers
[...]
```
In this example, JobSet creates a PVC, "pretrained-model" and then the created PV is mounted to replicatedJobs specified in the `.spec.volumePolicy.replicatedJobs`

This feature is similar to https://github.com/kubernetes/kubernetes/issues/115066

**Why is this needed**:
In large distributed training, we often store the base model, and then we want to share the pre-trained model with all workers so that we can avoid downloading the pre-trained model many times.
