### ISSUE TITLE
Trigger restart mechanism when node worker has been running on is shut down

### ISSUE THREAD

**Issue by qGentry** [kubernetes-sigs/jobset#574]
Hi, I'm quite new to JobSet and it seems to be a very handy tools for multi-node training jobs.
One problem I've noticed when going through examples and testing them is that for some reason JobSet doesn't trigger full restart mechanism when worker pod is killed manually (with `kubectl delete pod ...`) or when node this pod has been running on is shut down. 
Easiest example to reproduce this behavior is this spec:
```yaml
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: max-restarts
spec:
  failurePolicy:
    maxRestarts: 3
  replicatedJobs:
  - name: worker
    replicas: 1
    template:
      spec:
        backoffLimit: 0
        completions: 3
        parallelism: 3
        template:
          spec:
            containers:
            - name: leader
              image: bash:latest
              command:
              - bash
              - -xc
              - sleep 300
```

And then
```bash
> k apply -f jobset.yaml
jobset.jobset.x-k8s.io/max-restarts created
> k delete pod max-restarts-worker-0-1-2bn2v
> k get pods | grep max
max-restarts-worker-0-0-w8pjj                                       1/1     Running       0              74s
max-restarts-worker-0-1-2bn2v                                       1/1     Terminating   0              74s 
max-restarts-worker-0-1-dhg5x                                       1/1     Running       0              25s
max-restarts-worker-0-2-2t86z                                       1/1     Running       0              74s

> k describe job max-restarts-worker-0
...
Events:
  Type    Reason            Age    From            Message
  ----    ------            ----   ----            -------
  Normal  SuccessfulCreate  3m15s  job-controller  Created pod: max-restarts-worker-0-0-w8pjj
  Normal  SuccessfulCreate  3m15s  job-controller  Created pod: max-restarts-worker-0-2-2t86z
  Normal  SuccessfulCreate  3m15s  job-controller  Created pod: max-restarts-worker-0-1-2bn2v
  Normal  SuccessfulCreate  2m26s  job-controller  Created pod: max-restarts-worker-0-1-dhg5x

```

As you can see, new worker is created to replace old one instead of triggering full restart mechanism (which wouldn't work in torch.distributed or JAX environments)

**Comment by qGentry** [comment]
Also, I'm using k8s 1.24 and latest JobSet controller (0.5.0 i guess)

**Comment by danielvegamyhre** [comment]
Did you check `kubectl describe jobset <jobset name>`? You should see an event associated with the jobset indicating it restarted.

**Comment by qGentry** [comment]
yeah, I've checked jobset itself but these is no events after manually deleting pod
```
> k describe jobsets.jobset.x-k8s.io max-restarts
...
Events:         <none>
```
I believe that in case of manually deleting pod/node shutdown job restart is handled by Job, not by JobSet

**Comment by danielvegamyhre** [comment]
Currently, JobSet restarts if any child Job is marked as failed. If you manually delete a pod, and the Job is configured with `RestartPolicy: Never` and `backOffLimit: 0` then the Job will be marked as failed immediately and cause the jobset to restart.

**Comment by qGentry** [comment]
`backoffLimit` is already zero in my case.
I tried to add as much `restartPolicy: Never` as i could in jobset spec but still have same behavior - deleting pod doesn't trigger global JobSet restart mechanism but instead Job just recreates only deleted pod.

Here's my jobset spec.
```
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: max-restarts
spec:
  failurePolicy:
    maxRestarts: 3
  replicatedJobs:
  - name: worker
    replicas: 1
    template:
      spec:
        backoffLimit: 0
        completions: 3
        parallelism: 3
        template:
          spec:
            restartPolicy: Never
            containers:
            - name: leader
              image: bash:latest
              restartPolicy: Never
              command:
              - bash
              - -xc
              - sleep 300
```

Am i doing something wrong? Maybe there is another place in which i should include `restartPolicy: Never`?

**Comment by jessicaxiejw** [comment]
What version of jobset do you have in the cluster?

**Comment by qGentry** [comment]
I'm using 0.5.0 jobset version
https://github.com/kubernetes-sigs/jobset/issues/574#issuecomment-2115667179

Also, after some digging into, I've noticed that it may not be problem with JobSet itself but with Job. 
If I create a Job like this
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: max-restarts
spec:
  backoffLimit: 0
  completions: 3
  parallelism: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: leader
        image: bash:latest
        command: ["bash", "-xc", "sleep 300"]
```
and delete worker pod, it's getting immediately recreated instead of failing job (even though backoffLimit is 0 and restartPolicy is Never). Currently I'm trying to determine the cause of such behavior
