### ISSUE TITLE
Fix Bugs related to Configurable Failure Policy

### ISSUE THREAD

**Issue by jedwins1998** [kubernetes-sigs/jobset#588]
I am testing configurable failure policy manually and have discovered some bugs. Using this issue to track what I find.

**Comment by jedwins1998** [comment]
Line 106 in [`failure_policy.go`](https://github.com/kubernetes-sigs/jobset/blob/50290ebd57c5926bdb3ccb4491ef823f17d889a2/pkg/controllers/failure_policy.go#L106C3-L106C118) needs to be updated to
```
msg := fmt.Sprintf("did not find a failed job matching failure policy rule with index %v and name %v", index, rule.Name)
log.V(2).Info(msg)
```

**Comment by jedwins1998** [comment]
Omitting `onJobFailureReasons` currently does not work. I tried applying the YAML
```
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: failjobset-action-example
spec:
  # On failure, restart all jobs up to 3 times.
  failurePolicy:
    maxRestarts: 3
    rules:
      - action: FailJobSet
        targetReplicatedJobs:
        - leader
  replicatedJobs:
  - name: leader
    replicas: 1
    template:
      spec:
        # Set backoff limit to 0 so job will immediately fail if any pod fails.
        backoffLimit: 0
        completions: 2
        parallelism: 2
        template:
          spec:
            containers:
            - name: leader
              image: bash:latest
              # Default failure policy is to recreate all jobs if any jobs fails.
              # The bash script provides a simple demonstration of it by failing
              # the pod with completion index 0, which will trigger job failure
              # and the jobset controller wil recreate all jobs.
              command:
              - bash
              - -xc
              - |
                echo "JOB_COMPLETION_INDEX=$JOB_COMPLETION_INDEX"
                if [[ "$JOB_COMPLETION_INDEX" == "0" ]]; then
                  for i in $(seq 10 -1 1)
                  do
                    echo "Sleeping in $i"
                    sleep 1
                  done
                  exit 1
                fi
                for i in $(seq 1 1000)
                do
                  echo "$i"
                  sleep 1
                done
  - name: workers
    replicas: 1
    template:
      spec:
        backoffLimit: 0
        completions: 2
        parallelism: 2
        template:
          spec:
            containers:
            - name: worker
              image: bash:latest
              command:
              - bash
              - -xc
              - |
                sleep 1000
```
and received the error message
```
$ kubectl apply -f examples/failure-policy/failjobset-action.yaml 
The JobSet "failjobset-action-example" is invalid: 
* spec.failurePolicy.rules[0].onJobFailureReasons: Invalid value: "null": spec.failurePolicy.rules[0].onJobFailureReasons in body must be of type array: "null"
* <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation
```

I believe this is because `omitempty` needs to be added in line 268 of [jobset_types.go](https://github.com/jedwins1998/jobset/blob/50290ebd57c5926bdb3ccb4491ef823f17d889a2/api/jobset/v1alpha2/jobset_types.go#L268).
