### ISSUE TITLE
Annotations dropped from jobset spec

### ISSUE THREAD

**Issue by mattcary** [kubernetes-sigs/jobset#729]
Annotations for pods seem to be dropped. This is a regression from ~v0.5 as far as I can tell.

**What happened**:
Applied the following yaml:

```
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: test-annotations
  annotations:
    alpha.jobset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-nodepool
    jobset-level-annotation: "true"
spec:
  failurePolicy:
    maxRestarts: 0
  replicatedJobs:
  - name: main
    replicas: 1
    template:
      spec:
        parallelism: 1 # Should be smaller than the number of VMs
        completions: 1 # Same as the above.
        backoffLimit: 0   # When any pod fails, the job is failed
        template:
          metadata:
            annotations:
              template-level-annotation: "true"
          spec:
            containers:
            - name: benchmark
              image: busybox
              command: [ "sleep" ]
              args: [ "infinity" ]
```

The resulting pod annotations look like

```
Annotations:      alpha.jobset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-nodepool
                  batch.kubernetes.io/job-completion-index: 0
                  jobset.sigs.k8s.io/global-replicas: 1
                  jobset.sigs.k8s.io/job-global-index: 0
                  jobset.sigs.k8s.io/job-index: 0
                  jobset.sigs.k8s.io/job-key: 1cb0206240de13510151d6a13a8d1ea3747acf47
                  jobset.sigs.k8s.io/jobset-name: test-annotations
                  jobset.sigs.k8s.io/replicatedjob-name: main
                  jobset.sigs.k8s.io/replicatedjob-replicas: 1
                  jobset.sigs.k8s.io/restart-attempt: 0
```

**What you expected to happen**:

Expected `jobset-level-annotation: "true"` or `template-level-annotation: "true"` to appear on the pod.

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl apply --server-side -f https://github.com/kubernetes-sigs/jobset/releases/download/v0.7.1/manifests.yaml`,  `kubectl apply` the yaml above, then `kubectl describe pod` to see the annotations.

**Environment**:
- Kubernetes version (use `kubectl version`): 
  ```
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.31.2-gke.1518000
```
- JobSet version (use `git describe --tags --dirty --always`): v0.7.1 (see installation used above)
- Cloud provider or hardware configuration: GKE
