### ISSUE TITLE
How to retain failed pods

### ISSUE THREAD

**Issue by ltm920716** [kubernetes-sigs/jobset#776]
**What would you like to be added**:
Failed pods can be retained and their logs can be viewed like completed pods，at least the last maxRestarts pods could be retained

**Why is this needed**:
For LLM training, once a pod fails, the entire job will fail, and all failed pods will be automatically cleared. The reason for the failure cannot be viewed

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by ltm920716** [comment]
hi @kannon92 ，
I am sorry but could you help in this problem？thanks

**Comment by kannon92** [comment]
There is a TTLAfterFinished feature that could help persist these files.

**Comment by kannon92** [comment]
I'm not sure it is standard behavior that all failed pods are automatically cleared. There is a GC controller on K8s that will clean up pods based on the amount of pods on your system.

**Comment by ltm920716** [comment]
I  set ttlSecondsAfterFinished like bellow，but not work，all failed pods cleared soon

```
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: failed
spec:
  failurePolicy:
    maxRestarts: 0
  ttlSecondsAfterFinished: 180
  replicatedJobs:
  - name: trainjob
    template:
      spec:
        parallelism: 1
        completions: 1
        backoffLimit: 0
        ttlSecondsAfterFinished: 180
        template:
          spec:
            containers:
            - name: train-pod
              restartPolicy: Never
              image: nvcr.io/nvidia/pytorch:24.04-py3
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 2345
              resources:
                limits:
                  nvidia.com/gpu: 8
              command:
              - bash
              - -c
              - exit 1
              securityContext:
                capabilities:
                  add:
                  - IPC_LOCK

```
