### ISSUE TITLE
how does the parameter backoffLimit work？

### ISSUE THREAD

**Issue by ltm920716** [kubernetes-sigs/jobset#825]
**What happened**:
hi，I have thought that  `backoffLimit` is the restart number of pod in the same job-group，if `backoffLimit`  is 3， that there will be 3 times restart of the pod.  
I set parallelism=4，backoffLimit=3，and command the pod getting failed one by one. 
First of all，pod-0 failed

![Image](https://github.com/user-attachments/assets/d1a02e87-cc3c-4ee5-b867-692a9c46bc7b)

then，pod-0 restart new one

![Image](https://github.com/user-attachments/assets/ba29ae2d-395f-4878-83d0-36150beae126)

next，the new pod-0 failed

![Image](https://github.com/user-attachments/assets/a2d5bd70-a895-40e5-8829-87306238573b)

next，pod-1 failed

![Image](https://github.com/user-attachments/assets/bf098b76-026f-44ff-922b-1514ccd7205a)

next，pod-2 failed

![Image](https://github.com/user-attachments/assets/b5f6c81c-d602-4999-b476-1ebf102b9a5b)

next，pod-3 Terminating

![Image](https://github.com/user-attachments/assets/9487c6f9-29bc-4a1a-b338-a5b7a780b65c)

finally，pod-0、pod0 new、pod-1、pod-2 retained

![Image](https://github.com/user-attachments/assets/06493b04-33f7-4b45-b180-5142c1ced17b)

 it is very strange！

**What you expected to happen**:
I think when I set parallelism=4，backoffLimit=3，there will be 4 pods running，if one pod like pod-0 failed，it will creates new one， and then another pod failed，it still creates new one till to backoffLimit（3），but I get only one pod recreate.

one more thing, it should retain pod-0、pod-1、pod-2 、 pod-3, not pod-0、pod0 new、pod-1、pod-2 retained

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: failedl
spec:
  failurePolicy:
    maxRestarts: 4
  replicatedJobs:
  - name: trainjob
    template:
      spec:
        parallelism: 4
        completions: 8
        backoffLimit: 3
        template:
          spec:
            restartPolicy: Never
            nodeSelector:
              koo: node2
            containers:
            - name: train-pod
              image: nvcr.io/nvidia/pytorch:24.04-py3
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  nvidia.com/gpu: 1
              env:
              - name: RANK
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
              command:
              - bash
              - -c
              - sleep $((${RANK} * 20 + 3)); echo hello-${RANK}; exit 1
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- JobSet version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:
